/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.quizscuola.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.quizscuola.portlet.model.Argomento;
import it.quizscuola.portlet.model.ArgomentoModel;
import it.quizscuola.portlet.model.ArgomentoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Argomento service. Represents a row in the &quot;quiz_Argomento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.quizscuola.portlet.model.ArgomentoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArgomentoImpl}.
 * </p>
 *
 * @author Salvatore
 * @see ArgomentoImpl
 * @see it.quizscuola.portlet.model.Argomento
 * @see it.quizscuola.portlet.model.ArgomentoModel
 * @generated
 */
@JSON(strict = true)
public class ArgomentoModelImpl extends BaseModelImpl<Argomento>
	implements ArgomentoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a argomento model instance should use the {@link it.quizscuola.portlet.model.Argomento} interface instead.
	 */
	public static final String TABLE_NAME = "quiz_Argomento";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "idArgomento", Types.BIGINT },
			{ "descArgomento", Types.VARCHAR },
			{ "idMateria", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table quiz_Argomento (uuid_ VARCHAR(75) null,idArgomento LONG not null primary key,descArgomento VARCHAR(75) null,idMateria LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table quiz_Argomento";
	public static final String ORDER_BY_JPQL = " ORDER BY argomento.descArgomento ASC";
	public static final String ORDER_BY_SQL = " ORDER BY quiz_Argomento.descArgomento ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.quizscuola.portlet.model.Argomento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.quizscuola.portlet.model.Argomento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.quizscuola.portlet.model.Argomento"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long IDMATERIA_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long DESCARGOMENTO_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Argomento toModel(ArgomentoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Argomento model = new ArgomentoImpl();

		model.setUuid(soapModel.getUuid());
		model.setIdArgomento(soapModel.getIdArgomento());
		model.setDescArgomento(soapModel.getDescArgomento());
		model.setIdMateria(soapModel.getIdMateria());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Argomento> toModels(ArgomentoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Argomento> models = new ArrayList<Argomento>(soapModels.length);

		for (ArgomentoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.quizscuola.portlet.model.Argomento"));

	public ArgomentoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idArgomento;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdArgomento(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idArgomento;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Argomento.class;
	}

	@Override
	public String getModelClassName() {
		return Argomento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("idArgomento", getIdArgomento());
		attributes.put("descArgomento", getDescArgomento());
		attributes.put("idMateria", getIdMateria());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long idArgomento = (Long)attributes.get("idArgomento");

		if (idArgomento != null) {
			setIdArgomento(idArgomento);
		}

		String descArgomento = (String)attributes.get("descArgomento");

		if (descArgomento != null) {
			setDescArgomento(descArgomento);
		}

		Long idMateria = (Long)attributes.get("idMateria");

		if (idMateria != null) {
			setIdMateria(idMateria);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getIdArgomento() {
		return _idArgomento;
	}

	@Override
	public void setIdArgomento(long idArgomento) {
		_idArgomento = idArgomento;
	}

	@JSON
	@Override
	public String getDescArgomento() {
		if (_descArgomento == null) {
			return StringPool.BLANK;
		}
		else {
			return _descArgomento;
		}
	}

	@Override
	public void setDescArgomento(String descArgomento) {
		_columnBitmask = -1L;

		_descArgomento = descArgomento;
	}

	@JSON
	@Override
	public long getIdMateria() {
		return _idMateria;
	}

	@Override
	public void setIdMateria(long idMateria) {
		_columnBitmask |= IDMATERIA_COLUMN_BITMASK;

		if (!_setOriginalIdMateria) {
			_setOriginalIdMateria = true;

			_originalIdMateria = _idMateria;
		}

		_idMateria = idMateria;
	}

	public long getOriginalIdMateria() {
		return _originalIdMateria;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Argomento.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Argomento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Argomento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Argomento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArgomentoImpl argomentoImpl = new ArgomentoImpl();

		argomentoImpl.setUuid(getUuid());
		argomentoImpl.setIdArgomento(getIdArgomento());
		argomentoImpl.setDescArgomento(getDescArgomento());
		argomentoImpl.setIdMateria(getIdMateria());
		argomentoImpl.setGroupId(getGroupId());
		argomentoImpl.setCompanyId(getCompanyId());
		argomentoImpl.setUserId(getUserId());
		argomentoImpl.setUserName(getUserName());
		argomentoImpl.setCreateDate(getCreateDate());
		argomentoImpl.setModifiedDate(getModifiedDate());

		argomentoImpl.resetOriginalValues();

		return argomentoImpl;
	}

	@Override
	public int compareTo(Argomento argomento) {
		int value = 0;

		value = getDescArgomento().compareTo(argomento.getDescArgomento());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Argomento)) {
			return false;
		}

		Argomento argomento = (Argomento)obj;

		long primaryKey = argomento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ArgomentoModelImpl argomentoModelImpl = this;

		argomentoModelImpl._originalUuid = argomentoModelImpl._uuid;

		argomentoModelImpl._originalIdMateria = argomentoModelImpl._idMateria;

		argomentoModelImpl._setOriginalIdMateria = false;

		argomentoModelImpl._originalGroupId = argomentoModelImpl._groupId;

		argomentoModelImpl._setOriginalGroupId = false;

		argomentoModelImpl._originalCompanyId = argomentoModelImpl._companyId;

		argomentoModelImpl._setOriginalCompanyId = false;

		argomentoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Argomento> toCacheModel() {
		ArgomentoCacheModel argomentoCacheModel = new ArgomentoCacheModel();

		argomentoCacheModel.uuid = getUuid();

		String uuid = argomentoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			argomentoCacheModel.uuid = null;
		}

		argomentoCacheModel.idArgomento = getIdArgomento();

		argomentoCacheModel.descArgomento = getDescArgomento();

		String descArgomento = argomentoCacheModel.descArgomento;

		if ((descArgomento != null) && (descArgomento.length() == 0)) {
			argomentoCacheModel.descArgomento = null;
		}

		argomentoCacheModel.idMateria = getIdMateria();

		argomentoCacheModel.groupId = getGroupId();

		argomentoCacheModel.companyId = getCompanyId();

		argomentoCacheModel.userId = getUserId();

		argomentoCacheModel.userName = getUserName();

		String userName = argomentoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			argomentoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			argomentoCacheModel.createDate = createDate.getTime();
		}
		else {
			argomentoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			argomentoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			argomentoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return argomentoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", idArgomento=");
		sb.append(getIdArgomento());
		sb.append(", descArgomento=");
		sb.append(getDescArgomento());
		sb.append(", idMateria=");
		sb.append(getIdMateria());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("it.quizscuola.portlet.model.Argomento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idArgomento</column-name><column-value><![CDATA[");
		sb.append(getIdArgomento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descArgomento</column-name><column-value><![CDATA[");
		sb.append(getDescArgomento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idMateria</column-name><column-value><![CDATA[");
		sb.append(getIdMateria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Argomento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Argomento.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _idArgomento;
	private String _descArgomento;
	private long _idMateria;
	private long _originalIdMateria;
	private boolean _setOriginalIdMateria;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private Argomento _escapedModel;
}