/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.quizscuola.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Domanda service. Represents a row in the &quot;quiz_Domanda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.quizscuola.portlet.model.impl.DomandaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.quizscuola.portlet.model.impl.DomandaImpl}.
 * </p>
 *
 * @author Salvatore
 * @see Domanda
 * @see it.quizscuola.portlet.model.impl.DomandaImpl
 * @see it.quizscuola.portlet.model.impl.DomandaModelImpl
 * @generated
 */
public interface DomandaModel extends BaseModel<Domanda>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a domanda model instance should use the {@link Domanda} interface instead.
	 */

	/**
	 * Returns the primary key of this domanda.
	 *
	 * @return the primary key of this domanda
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this domanda.
	 *
	 * @param primaryKey the primary key of this domanda
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this domanda.
	 *
	 * @return the uuid of this domanda
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this domanda.
	 *
	 * @param uuid the uuid of this domanda
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id domanda of this domanda.
	 *
	 * @return the id domanda of this domanda
	 */
	public long getIdDomanda();

	/**
	 * Sets the id domanda of this domanda.
	 *
	 * @param idDomanda the id domanda of this domanda
	 */
	public void setIdDomanda(long idDomanda);

	/**
	 * Returns the desc domanda of this domanda.
	 *
	 * @return the desc domanda of this domanda
	 */
	@AutoEscape
	public String getDescDomanda();

	/**
	 * Sets the desc domanda of this domanda.
	 *
	 * @param descDomanda the desc domanda of this domanda
	 */
	public void setDescDomanda(String descDomanda);

	/**
	 * Returns the id argomento of this domanda.
	 *
	 * @return the id argomento of this domanda
	 */
	public long getIdArgomento();

	/**
	 * Sets the id argomento of this domanda.
	 *
	 * @param idArgomento the id argomento of this domanda
	 */
	public void setIdArgomento(long idArgomento);

	/**
	 * Returns the group ID of this domanda.
	 *
	 * @return the group ID of this domanda
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this domanda.
	 *
	 * @param groupId the group ID of this domanda
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this domanda.
	 *
	 * @return the company ID of this domanda
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this domanda.
	 *
	 * @param companyId the company ID of this domanda
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this domanda.
	 *
	 * @return the user ID of this domanda
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this domanda.
	 *
	 * @param userId the user ID of this domanda
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this domanda.
	 *
	 * @return the user uuid of this domanda
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this domanda.
	 *
	 * @param userUuid the user uuid of this domanda
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this domanda.
	 *
	 * @return the user name of this domanda
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this domanda.
	 *
	 * @param userName the user name of this domanda
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this domanda.
	 *
	 * @return the create date of this domanda
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this domanda.
	 *
	 * @param createDate the create date of this domanda
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this domanda.
	 *
	 * @return the modified date of this domanda
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this domanda.
	 *
	 * @param modifiedDate the modified date of this domanda
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the posizione of this domanda.
	 *
	 * @return the posizione of this domanda
	 */
	public int getPosizione();

	/**
	 * Sets the posizione of this domanda.
	 *
	 * @param posizione the posizione of this domanda
	 */
	public void setPosizione(int posizione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Domanda domanda);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Domanda> toCacheModel();

	@Override
	public Domanda toEscapedModel();

	@Override
	public Domanda toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}