/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.quizscuola.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Risposta service. Represents a row in the &quot;quiz_Risposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.quizscuola.portlet.model.impl.RispostaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.quizscuola.portlet.model.impl.RispostaImpl}.
 * </p>
 *
 * @author Salvatore
 * @see Risposta
 * @see it.quizscuola.portlet.model.impl.RispostaImpl
 * @see it.quizscuola.portlet.model.impl.RispostaModelImpl
 * @generated
 */
public interface RispostaModel extends BaseModel<Risposta>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a risposta model instance should use the {@link Risposta} interface instead.
	 */

	/**
	 * Returns the primary key of this risposta.
	 *
	 * @return the primary key of this risposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this risposta.
	 *
	 * @param primaryKey the primary key of this risposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this risposta.
	 *
	 * @return the uuid of this risposta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this risposta.
	 *
	 * @param uuid the uuid of this risposta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id risposta of this risposta.
	 *
	 * @return the id risposta of this risposta
	 */
	public long getIdRisposta();

	/**
	 * Sets the id risposta of this risposta.
	 *
	 * @param idRisposta the id risposta of this risposta
	 */
	public void setIdRisposta(long idRisposta);

	/**
	 * Returns the desc risposta of this risposta.
	 *
	 * @return the desc risposta of this risposta
	 */
	@AutoEscape
	public String getDescRisposta();

	/**
	 * Sets the desc risposta of this risposta.
	 *
	 * @param descRisposta the desc risposta of this risposta
	 */
	public void setDescRisposta(String descRisposta);

	/**
	 * Returns the esatta of this risposta.
	 *
	 * @return the esatta of this risposta
	 */
	public boolean getEsatta();

	/**
	 * Returns <code>true</code> if this risposta is esatta.
	 *
	 * @return <code>true</code> if this risposta is esatta; <code>false</code> otherwise
	 */
	public boolean isEsatta();

	/**
	 * Sets whether this risposta is esatta.
	 *
	 * @param esatta the esatta of this risposta
	 */
	public void setEsatta(boolean esatta);

	/**
	 * Returns the id domanda of this risposta.
	 *
	 * @return the id domanda of this risposta
	 */
	public long getIdDomanda();

	/**
	 * Sets the id domanda of this risposta.
	 *
	 * @param idDomanda the id domanda of this risposta
	 */
	public void setIdDomanda(long idDomanda);

	/**
	 * Returns the group ID of this risposta.
	 *
	 * @return the group ID of this risposta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this risposta.
	 *
	 * @param groupId the group ID of this risposta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this risposta.
	 *
	 * @return the company ID of this risposta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this risposta.
	 *
	 * @param companyId the company ID of this risposta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this risposta.
	 *
	 * @return the user ID of this risposta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this risposta.
	 *
	 * @param userId the user ID of this risposta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this risposta.
	 *
	 * @return the user uuid of this risposta
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this risposta.
	 *
	 * @param userUuid the user uuid of this risposta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this risposta.
	 *
	 * @return the user name of this risposta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this risposta.
	 *
	 * @param userName the user name of this risposta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this risposta.
	 *
	 * @return the create date of this risposta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this risposta.
	 *
	 * @param createDate the create date of this risposta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this risposta.
	 *
	 * @return the modified date of this risposta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this risposta.
	 *
	 * @param modifiedDate the modified date of this risposta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Risposta risposta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Risposta> toCacheModel();

	@Override
	public Risposta toEscapedModel();

	@Override
	public Risposta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}