/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.quizscuola.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Argomento service. Represents a row in the &quot;Quiz_Argomento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.quizscuola.portlet.model.impl.ArgomentoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.quizscuola.portlet.model.impl.ArgomentoImpl}.
 * </p>
 *
 * @author Salvatore
 * @see Argomento
 * @see it.quizscuola.portlet.model.impl.ArgomentoImpl
 * @see it.quizscuola.portlet.model.impl.ArgomentoModelImpl
 * @generated
 */
public interface ArgomentoModel extends BaseModel<Argomento>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a argomento model instance should use the {@link Argomento} interface instead.
	 */

	/**
	 * Returns the primary key of this argomento.
	 *
	 * @return the primary key of this argomento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this argomento.
	 *
	 * @param primaryKey the primary key of this argomento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this argomento.
	 *
	 * @return the uuid of this argomento
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this argomento.
	 *
	 * @param uuid the uuid of this argomento
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id argomento of this argomento.
	 *
	 * @return the id argomento of this argomento
	 */
	public long getIdArgomento();

	/**
	 * Sets the id argomento of this argomento.
	 *
	 * @param idArgomento the id argomento of this argomento
	 */
	public void setIdArgomento(long idArgomento);

	/**
	 * Returns the desc argomento of this argomento.
	 *
	 * @return the desc argomento of this argomento
	 */
	@AutoEscape
	public String getDescArgomento();

	/**
	 * Sets the desc argomento of this argomento.
	 *
	 * @param descArgomento the desc argomento of this argomento
	 */
	public void setDescArgomento(String descArgomento);

	/**
	 * Returns the id materia of this argomento.
	 *
	 * @return the id materia of this argomento
	 */
	public long getIdMateria();

	/**
	 * Sets the id materia of this argomento.
	 *
	 * @param idMateria the id materia of this argomento
	 */
	public void setIdMateria(long idMateria);

	/**
	 * Returns the group ID of this argomento.
	 *
	 * @return the group ID of this argomento
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this argomento.
	 *
	 * @param groupId the group ID of this argomento
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this argomento.
	 *
	 * @return the company ID of this argomento
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this argomento.
	 *
	 * @param companyId the company ID of this argomento
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this argomento.
	 *
	 * @return the user ID of this argomento
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this argomento.
	 *
	 * @param userId the user ID of this argomento
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this argomento.
	 *
	 * @return the user uuid of this argomento
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this argomento.
	 *
	 * @param userUuid the user uuid of this argomento
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this argomento.
	 *
	 * @return the user name of this argomento
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this argomento.
	 *
	 * @param userName the user name of this argomento
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this argomento.
	 *
	 * @return the create date of this argomento
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this argomento.
	 *
	 * @param createDate the create date of this argomento
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this argomento.
	 *
	 * @return the modified date of this argomento
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this argomento.
	 *
	 * @param modifiedDate the modified date of this argomento
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Argomento argomento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Argomento> toCacheModel();

	@Override
	public Argomento toEscapedModel();

	@Override
	public Argomento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}